name: Check PR State

on:
  pull_request:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  check_pr_state:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get PR State
        id: pr_state
        run: |
          PR_STATE=$(gh pr list --json state)
          echo "::set-output name=pr_state::$PR_STATE"

      - name: Display PR State
        run: |
          echo "PR State: ${{ steps.pr_state.outputs.pr_state }}"
