name: Auto Comment Conflicts

on:
  pull_request:
  # schedule:
  # - cron: '*/1 * * * *'

permissions:
  contents: read
      
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  prList:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get PR List
        run: |
          gh pr list -L 100 --json number,mergeable,url,labels,author > pr_list.json

      - name: Add label "stale" and comment
        run: |
          for item in $(cat pr_list.json | jq -r '.[] | @base64'); do
            decoded=$(echo $item | base64 --decode)
            mergeable=$(echo $decoded | jq -r '.mergeable')
            labels=$(echo $decoded | jq -r '.labels[].name')
            number=$(echo $decoded | jq -r '.number')
            url=$(echo $decoded | jq -r '.url')
            author=$(echo $decoded | jq -r '.author.login')

            echo "PR $number is $mergeable. URL: $url with Author: $author" 

            if [[ "$mergeable" == "CONFLICTING" && "$labels" != *"stale"* ]]; then
              gh pr edit $url --add-label "stale"
              gh pr comment $url --body ":wave: Hi, @$author!<br><br>We detected conflicts in your PR against the base branch :speak_no_evil:<br>You may want to sync :arrows_counterclockwise: your branch with upstream!<br><br>Ref: [Syncing Your Branch](https://github.com/codeigniter4/CodeIgniter4/blob/develop/contributing/workflow.md#pushing-your-branch)"
            fi
          done

      - name: Remove Label "stale"
        run: |
          for item in $(cat pr_list.json | jq -r '.[] | @base64'); do
            decoded=$(echo $item | base64 --decode)
            mergeable=$(echo $decoded | jq -r '.mergeable')
            labels=$(echo $decoded | jq -r '.labels[].name')
            url=$(echo $decoded | jq -r '.url')

            if [[ "$mergeable" != "CONFLICTING" && "$labels" == *"stale"* ]]; then
              gh pr edit $url --remove-label "stale"
            fi
          done
